project:
  type: website

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

website:
  title: "Sayak Paul"
  site-url: "https://adtygan.github.io/"
  description: "Personal site of Sayak Paul."
  favicon: posts/favicon.ico
  search: false
  twitter-card:
    creator: "@RisingSayak"
    card-style: summary
  open-graph: true
  repo-actions: [edit, issue]
  repo-branch: "master"
  repo-url: "https://github.com/adtygan/adtygan.github.io"
  #google-analytics: "UA-163448909-1"
  navbar:
    background: primary
    left:
      - text: "About Me"
        href: pages/about.qmd
      - text: "Authoring"
        href: pages/authoring.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Research"
        href: pages/research.qmd
      - text: "Resources"
        href: pages/resources.qmd
    right:
      - icon: twitter
        href: https://twitter.com/RisingSayak
      - icon: linkedin
        href: https://www.linkedin.com/in/sayak-paul/
      - icon: github
        href: https://github.com/sayakpaul

execute:
  freeze: auto

resources:
  - CNAME